export const allTags = [
    "Foodie",
    "Cooking",
    "Restaurants",
    "Street Food",
    "Sushi",
    "Vegetarian",
    "Vegan",
    "Gym",
    "Yoga",
    "Sports Enthusiast",
    "Basketball",
    "Soccer",
    "Football",
    "Hockey",
    "Baseball",
    "NBA",
    "NFL",
    "NHL",
    "MLB",
    "Dancing",
    "Martial Arts",
    "Astrology",
    "90s Kid",
    "History",
    "Thrifting",
    "Vintages",
    "Antiques",
    "Trying New Things",
    "Party Animal",
    "Going Out",
    "Staying In",
    "Dogs",
    "Cats",
    "Anime",
    "Art",
    "DIY",
    "Movies",
    "Star Wars",
    "Marvel/DC",
    "Netflix",
    "K-Dramas",
    "Study Cafes",
    "Adventures",
    "Hiking",
    "Bird Watching",
    "The Beach",
    "Boating/Sailing",
    "Nature",
    "Traveling",
    "Shopping",
    "Fashion",
    "Sneakerhead",
    "Book Worm",
    "Astronomy",
    "Music",
    "Bands",
    "Concerts",
    "K-Pop",
    "Video Games", 
    "Cars",
    "Geek",
    "Technology",
    "Study Buddy",
    "Casual",
    "Serious",
    "Long-Term",
  ];